markdown: kramdown
remote_theme: hydecorp/hydejack
url: https://shicode.github.io
baseurl:               ''

plugins:
  - jekyll-paginate
  - jekyll-avatar
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-include-cache
  - jekyll-last-modified-at
  - jemoji

paginate:      10
paginate_path: '/:num/'

title: Shilpa Suresh
description:  >
 MS in Computer Science, UMass-Amherst
logo: /images/oregon_coast.jpg 

copyright: © 2021. All rights reserved.

font:         Noto Sans, Helvetica, Arial, sans-serif
font_heading: Roboto Slab, Helvetica, Arial, sans-serif
google_fonts: Roboto+Slab:700|Noto+Sans:400,400i,700,700i

menu:
  - title: Blog
    url:   
  - title: Projects
    url:   /projects/
  - title: Resume
    url:   /resume/
  - title: About
    url:   /about/

author:
  name:  Shilpa Suresh
  email: ssuresh@umass.edu
  about: |
    Hi, I'm Shilpa 

    This is another paragraph.
  picture:  /assets/img/me.jpg
  social:
    twitter: shilpa15397
    github:  shicode
    email:    ssuresh@umass.edu

