markdown: kramdown
remote_theme: hydecorp/hydejack
plugins:
  - jekyll-paginate
  - jekyll-avatar
paginate:      10
paginate_path: '/:num/'

font:         Noto Sans, Helvetica, Arial, sans-serif
font_heading: Roboto Slab, Helvetica, Arial, sans-serif
google_fonts: Roboto+Slab:700|Noto+Sans:400,400i,700,700i

menu:
  - title: Blog
    url:   /blog.md
  - title: Projects
    url:   /projects/
  - title: Resume
    url:   /resume/
  - title: About
    url:   /about/

author:
  name:  Shilpa Suresh
  email: ssuresh@umass.edu
  about: |
    Hi, I'm Shilpa 

    This is another paragraph.
  picture:  /assets/img/me.jpg
  social:
    twitter: shilpa15397
    github:  shicode
    email:    ssuresh@umass.edu