markdown: kramdown
remote_theme: hydecorp/hydejack
#accent_image: ../images/oregon_coast.jpg
#accent_color: rgb(79,177,186)

menu:
  - title: Blog
    url:   /blog/
  - title: Projects
    url:   /projects/
  - title: Resume
    url:   /resume/
  - title: About
    url:   /about/